### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by drdaz** [Wolox/WLXBluetoothDevice#44]
Since there doesn't seem to be a dependency on ReactiveCocoa anymore, perhaps re-adding CocoaPods support would be in order?

**Comment by guidomb** [comment]
This issue is already been tracked in #40. It hasn't been a priority for me because I'm not using Cocoapods for my projects anymore. I'll try to add it as soon as I can. PR are welcomed!. I'll close this issue. Any further discussion about Cocoapods should happen in #40.

Thanks!
